### ISSUE TITLE
Use ESLint

### ISSUE THREAD

**Issue by Sixstring982** [codeclubs-dot-org/codeclubs.org#10]
We should set up some linting rules.

**Comment by paul-perez** [comment]
ESlint is already set in the project. You should see linting errors in your command prompt where you are running npm start as well as in the browser console in real time.

**Comment by Sixstring982** [comment]
We can configure eslint via `./package.json`. We may want to add an eslintrc if we want to add more rules.

**Comment by paul-perez** [comment]
Also standardJS is installed as a dev dependency. to fix code run 'npx standard --fix'

**Comment by Sixstring982** [comment]
Sounds good, we're using standardjs.
